services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass the desired mode to the Dockerfile at build time
        VITE_ENV_MODE: staging
    container_name: pern-stack
    ports:
      - "3000:3000"
    env_file:
      - .env.staging